### ISSUE TITLE
Works with Sublime Text 3

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [Pold87/myPDDL#1]
Thank you for an awesome plugin/tool.  Just wanted to note that it works really well with Sublime Text 3 as well as previous versions.

Cheers,
Nap

**Comment by corot** [comment]
Hi, @Napoleon-BlownApart, I'm trying to use myPDDL with Sublime Text 3 and is not working to me (or at least I don't understand what he is doing). I follow the instructions of the readme to create a new PDDL project: (ctrl+shift+p) and choose myPDDL-new. But when I type enter, nothing happens! Same for the other commands apart from switching to PDDL syntax.

So did you need any additional configuration appart from setting

```
path=~/.config/sublime-text-3/Packages/myPDDL
```

instead of 

```
path=~/.config/sublime-text-2/Packages/myPDDL
```

?

Some extra information: I use Kubuntu 14.04 and an unregistered Sublime Text 3 installed with apt-get.

Thanks!

**Comment by Napoleon-BlownApart** [comment]
I downloaded the 'sublime-text_build-3083_amd64.deb' package and installed it.

I used the git clone version of myPDDL and put all the files into the '~/.config/sublime-text-3/Packages/myPDDL' folder.

I then moved the file "myPDDL" into '/usr/local/bin', made it executable (a+x) and made sure the paths inside it were accurate.

Since I had a number of existing PDDL files, I just opened them in Sublime Text and they were displayed correctly.  At the bottom right of the Sublime Text window is a button that allows you can change the parsing rules.  I made sure it was set on PDDL.  I think using an existing PDDL file to verify its working is a good starting point.

I haven't used the "New Project" feature much, because my existing file structure is different, but it did work fine for me, and I'll use it when I create new projects in the future.

Hope this helps.

**Comment by corot** [comment]
Hi again, I have repeated your steps and all works now perfectly! Thanks
